### ISSUE TITLE
Error when running aggregate 

### ISSUE THREAD

**Issue by Cyan331** [ELELAB/RosettaDDGPrediction#69]
Hello,
I am having this error when running the aggregate step, it seems having problem with opening the db3 file. The error is attached below. Many thanks!

rosetta_ddg_aggregate -cr flexddg_talaris2014 -cs nompi -mf mutinfo.txt

2024-07-21 19:28:13,481 - distributed.worker - WARNING - Compute Failed
Key:       parse_output_flexddg-352c4c2afe030541cf4e3242bb29cccc
State:     executing
Function:  parse_output_flexddg
args:      ()
kwargs:    {'db3_out': '/home/chenbo/RosettaDDGPrediction/washcap/flexddg/flexddg/C-G2A/1/ddg.db3', 'traj_stride': 5, 'struct_num': '1', 'scf_name': 'talaris2014'}
Exception: "OperationalError('unable to open database file')"
Traceback: '  File "/home/chenbo/anaconda3/lib/python3.9/site-packages/RosettaDDGPrediction-0.0.1-py3.9.egg/RosettaDDGPrediction/aggregation.py", line 177, in parse_output_flexddg\n    connection = sqlite3.connect(db3_out)\n'

Traceback (most recent call last):
  File "/home/chenbo/anaconda3/bin/rosetta_ddg_aggregate", line 33, in <module>
    sys.exit(load_entry_point('RosettaDDGPrediction==0.0.1', 'console_scripts', 'rosetta_ddg_aggregate')())
  File "/home/chenbo/anaconda3/lib/python3.9/site-packages/RosettaDDGPrediction-0.0.1-py3.9.egg/RosettaDDGPrediction/rosetta_ddg_aggregate.py", line 493, in main
  File "/home/chenbo/anaconda3/lib/python3.9/site-packages/distributed/client.py", line 392, in result
    return self.client.sync(self._result, callback_timeout=timeout)
  File "/home/chenbo/anaconda3/lib/python3.9/site-packages/RosettaDDGPrediction-0.0.1-py3.9.egg/RosettaDDGPrediction/aggregation.py", line 177, in parse_output_flexddg
sqlite3.OperationalError: unable to open database file

**Comment by mtiberti** [comment]
hi @Cyan331 , sorry for the delayed answer. As you mention it looks like it cannot read that file specifically.

Has the run that generated these data completed correctly? Does the file exist and is it readable?

**Comment by jlingford** [comment]
Hi, not sure if this is the same issue @Cyan331 is having, but I've noticed what appears to be a bug with the `rosetta_ddg_aggregate` functions `-mf` option.

If I provide a path/to/mutinfo.txt that isn't default, it throws an error. E.g.:

Input:
```
# set variables
CONFIG_RUN=RosettaDDGPrediction/config_run
CONFIG_SET=RosettaDDGPrediction/config_settings
CONFIG_AGG=RosettaDDGPrediction/config_aggregate

rosetta_ddg_aggregate \
    -ca $CONFIG_AGG/aggregate.yaml \
    -cr $CONFIG_RUN/flexddg_ref2015.yaml \
    -cs $CONFIG_SET/rosettampi.yaml \
    -mf backup_data_flexddg_P44T/flexddg/mutinfo.txt \
    -od test
```

Errors:
```
WARNING:root:The configuration file did not specify whether to launch the Rosetta executables with MPI or it specified not to. However, either the MPI executable ('mpiexec') or the MPI arguments ('mpiargs') have been passed. These options will be ignored.
2024-12-19 12:32:09,877 - distributed.worker - ERROR - Compute Failed
Key:       parse_output_flexddg-195fc6bc8c25210c76d1e6d5280b416e
State:     executing
Function:  parse_output_flexddg
args:      ()
kwargs:    {'db3_out': '/home/james/Documents/protein_struct_tools/ddg_rosetta/flexddg/A-P44T_B-P44T/1/ddg.db3', 'traj_stride': 5, 'struct_num': '1', 'scf_name': 'ref2015'}
Exception: "OperationalError('unable to open database file')"
Traceback: '  File "/home/james/micromamba/envs/ddg_rosetta/lib/python3.12/site-packages/RosettaDDGPrediction-0.0.1-py3.12.egg/RosettaDDGPrediction/aggregation.py", line 177, in parse_output_flexddg\n    connection = sqlite3.connect(db3_out)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^\n'

Traceback (most recent call last):
  File "/home/james/micromamba/envs/ddg_rosetta/bin/rosetta_ddg_aggregate", line 33, in <module>
    sys.exit(load_entry_point('RosettaDDGPrediction==0.0.1', 'console_scripts', 'rosetta_ddg_aggregate')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/micromamba/envs/ddg_rosetta/lib/python3.12/site-packages/RosettaDDGPrediction-0.0.1-py3.12.egg/RosettaDDGPrediction/rosetta_ddg_aggregate.py", line 493, in main
  File "/home/james/micromamba/envs/ddg_rosetta/lib/python3.12/site-packages/distributed/client.py", line 401, in result
    return self.client.sync(self._result, callback_timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/micromamba/envs/ddg_rosetta/lib/python3.12/site-packages/RosettaDDGPrediction-0.0.1-py3.12.egg/RosettaDDGPrediction/aggregation.py", line 177, in parse_output_flexddg

```

But if I stick with the default path/to/mutinfo.txt, and the `flexddg` dir is located in the current dir, it works as expected: E.g.

Input:
```
rosetta_ddg_aggregate \
    -ca $CONFIG_AGG/aggregate.yaml \
    -cr $CONFIG_RUN/flexddg_ref2015.yaml \
    -cs $CONFIG_SET/rosettampi.yaml \
    -mf flexddg/mutinfo1.txt \
    -od test
```

Output:
```
WARNING:root:The configuration file did not specify whether to launch the Rosetta executables with MPI or it specified not to. However, either the MPI executable ('mpiexec') or the MPI arguments ('mpiargs') have been passed. These options will be ignored.
```

**Comment by mtiberti** [comment]
hi @Cyan331 and @jlingford ,

I ran a couple of tests, to me it looks like the problem is not the location of the `mutinfo.txt` file; e.g. this command runs fine for me, when run in the main directory of a RosettaDDGPrediction run:

```
rosetta_ddg_aggregate -ca aggregate.yaml -cr cartddg2020_ref2015.yaml -cs rosettampi.yaml -od tesrt -mf /tmp/mutinfo.txt
```

to me the main problem is that `rosetta_ddg_aggregate` only works when the RosettaDDGRun of interest has been completed in the current folder where aggregate is run from (so for instance, there need to be `flexddg` or `cartesian` in the folder where `rosetta_ddg_aggregate` is run). This could have made more explicit in the error or in the documentation, or we could consider adding an option to select a target folder

**Comment by mtiberti** [comment]
I've added the information to the manual as specified in my earlier message
