### ISSUE TITLE
rosetta_ddg_run crashes without mutation list

### ISSUE THREAD

**Issue by tiffanyformosa** [ELELAB/RosettaDDGPrediction#70]
I am using RosettaDDG to predict the stability of some mutated proteins I identified through variant calling and colabfold. Since some of the mutations involved were frameshifts, I decided to call RosettaDDG directly on the mutated protein PDB file without setting the -l flag.

I received this INFO message, which is what I expected.
INFO:root:No list of mutations was passed. Therefore, no mutations will be performed.

However, rosetta_ddg_run then crashes with the following traceback:

Traceback (most recent call last):
  File "/mnt/references/programs/conda-envs/RosettaDDGPrediction/bin/rosetta_ddg_run", line 33, in <module>
    sys.exit(load_entry_point('RosettaDDGPrediction==0.0.1', 'console_scripts', 'rosetta_ddg_run')())
  File "/mnt/references/programs/conda-envs/RosettaDDGPrediction/lib/python3.7/site-packages/RosettaDDGPrediction-0.0.1-py3.7.egg/RosettaDDGPrediction/rosetta_ddg_run.py", line 432, in main
UnboundLocalError: local variable 'mut_options' referenced before assignment

It looks like rosetta_ddg_run without mutation list is not fully implemented. Could this be fixed?

**Comment by elenapapaleo** [comment]
no by design,  our rosetta workflow cannot be run without a mutation list (== file with mutations to be performed  or with positions if it is saturation). If you want to use selected mutations you need -l mutlist with the specific mutations; if it is saturation you need -l poslist with position --saturation and --reslist with the aa that each position must be mutated to.
