### ISSUE TITLE
Inconsistent execution of RosettaDDGPrediction on slurm. Seeking troubleshooting advice

### ISSUE THREAD

**Issue by platanifolia** [ELELAB/RosettaDDGPrediction#72]
Hello. I would like to seek advice on using RosettaDDGPrediction on a Slurm cluster. My Slurm script is roughly as follows:

```
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 16
#SBATCH --mem=96gb
#SBATCH --time=96:00:00
#SBATCH --partition=cpu
#SBATCH --job-name=...
#SBATCH --output=...
#SBATCH --error=...

some environment settings

rosetta_ddg_run -n 16 -p xxx.pdb -cr flexddg_ref2015.yaml -cs nompi.yaml -r "${rosetta_dict}" -l xxx.txt
```

However, the issue is that some tasks submitted in this manner run successfully and yield the expected results, while others return errors. I would like to inquire if you have encountered this kind of error, and what might be the possible causes for such errors?

Error report sample:

```
INFO:root:Now checking the configuration file /mnt/rna01//others/rosettaDDGPrediction/RosettaDDGPrediction_v0.0.1/RosettaDDGPrediction/config_settings/nompi.yaml.
/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/node.py:182: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 46511 instead
  warnings.warn(
INFO:root:Now checking the configuration file /mnt/rna01/user/others/rosettaDDGPrediction/RosettaDDGPrediction_v0.0.1/RosettaDDGPrediction/config_run/flexddg_ref2015_lite.yaml.
/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/Bio/PDB/StructureBuilder.py:100: PDBConstructionWarning: WARNING: Chain G is discontinuous at line 18429.
  warnings.warn(
/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/Bio/PDB/StructureBuilder.py:100: PDBConstructionWarning: WARNING: Chain H is discontinuous at line 18736.
  warnings.warn(
/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/Bio/PDB/StructureBuilder.py:100: PDBConstructionWarning: WARNING: Chain L is discontinuous at line 18791.
  warnings.warn(
/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/Bio/PDB/StructureBuilder.py:100: PDBConstructionWarning: WARNING: Chain G is discontinuous at line 18806.
  warnings.warn(
INFO:root:The following mutations will be performed:
H-D99A.
2024-09-13 16:47:34,290 - distributed.scheduler - WARNING - Worker failed to heartbeat for 1079s; attempting restart: <WorkerState 'tcp://127.0.0.1:35377', name: 2, status: running, memory: 0, processing: 2>
2024-09-13 16:47:34,290 - distributed.scheduler - WARNING - Worker failed to heartbeat for 1079s; attempting restart: <WorkerState 'tcp://127.0.0.1:39343', name: 3, status: running, memory: 0, processing: 2>
2024-09-13 16:47:34,291 - distributed.scheduler - WARNING - Worker failed to heartbeat for 1079s; attempting restart: <WorkerState 'tcp://127.0.0.1:42137', name: 0, status: running, memory: 0, processing: 2>
2024-09-13 16:47:34,291 - distributed.scheduler - WARNING - Worker failed to heartbeat for 1079s; attempting restart: <WorkerState 'tcp://127.0.0.1:43285', name: 1, status: running, memory: 0, processing: 2>
2024-09-13 16:47:34,291 - distributed.scheduler - WARNING - Worker failed to heartbeat for 1079s; attempting restart: <WorkerState 'tcp://127.0.0.1:45409', name: 4, status: running, memory: 0, processing: 2>
2024-09-13 16:47:38,297 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2024-09-13 16:47:38,297 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2024-09-13 16:47:38,299 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2024-09-13 16:47:38,299 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2024-09-13 16:47:38,299 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2024-09-13 16:47:38,310 - distributed.nanny - WARNING - Restarting worker
2024-09-13 17:01:33,731 - distributed.core - ERROR - Exception while handling op kill
Traceback (most recent call last):
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/core.py", line 829, in _handle_comm
    result = await result
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/nanny.py", line 400, in kill
    await self.process.kill(reason=reason, timeout=timeout)
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/nanny.py", line 879, in kill
    await process.join(max(0, deadline - time()))
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/utils.py", line 1957, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2024-09-13 17:01:33,997 - distributed.core - ERROR - Exception while handling op kill
Traceback (most recent call last):
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/core.py", line 829, in _handle_comm
    result = await result
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/nanny.py", line 400, in kill
    await self.process.kill(reason=reason, timeout=timeout)
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/nanny.py", line 879, in kill
    await process.join(max(0, deadline - time()))
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/utils.py", line 1957, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2024-09-13 17:01:33,998 - distributed.core - ERROR - Exception while handling op kill
Traceback (most recent call last):
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/core.py", line 829, in _handle_comm
    result = await result
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/nanny.py", line 400, in kill
    await self.process.kill(reason=reason, timeout=timeout)
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/nanny.py", line 879, in kill
    await process.join(max(0, deadline - time()))
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/utils.py", line 1957, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2024-09-13 17:01:34,000 - distributed.core - ERROR - Exception while handling op kill
Traceback (most recent call last):
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/core.py", line 829, in _handle_comm
    result = await result
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/nanny.py", line 400, in kill
    await self.process.kill(reason=reason, timeout=timeout)
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/nanny.py", line 879, in kill
    await process.join(max(0, deadline - time()))
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/utils.py", line 1957, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2024-09-13 17:01:34,007 - distributed.scheduler - ERROR - Workers ['tcp://127.0.0.1:45409', 'tcp://127.0.0.1:42137', 'tcp://127.0.0.1:43285', 'tcp://127.0.0.1:39343'] did not shut down within 30s; force closing
2024-09-13 17:01:34,013 - distributed.scheduler - ERROR - 4/5 nanny worker(s) did not shut down within 30s: {'tcp://127.0.0.1:45409', 'tcp://127.0.0.1:42137', 'tcp://127.0.0.1:43285', 'tcp://127.0.0.1:39343'}
Traceback (most recent call last):
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/scheduler.py", line 6454, in restart_workers
    raise TimeoutError(
asyncio.exceptions.TimeoutError: 4/5 nanny worker(s) did not shut down within 30s: {'tcp://127.0.0.1:45409', 'tcp://127.0.0.1:42137', 'tcp://127.0.0.1:43285', 'tcp://127.0.0.1:39343'}
2024-09-13 17:01:34,013 - distributed.scheduler - ERROR - 4/5 nanny worker(s) did not shut down within 30s: {'tcp://127.0.0.1:45409', 'tcp://127.0.0.1:42137', 'tcp://127.0.0.1:43285', 'tcp://127.0.0.1:39343'}
Traceback (most recent call last):
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/scheduler.py", line 8492, in check_worker_ttl
    await self.restart_workers(
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/scheduler.py", line 6454, in restart_workers
    raise TimeoutError(
asyncio.exceptions.TimeoutError: 4/5 nanny worker(s) did not shut down within 30s: {'tcp://127.0.0.1:45409', 'tcp://127.0.0.1:42137', 'tcp://127.0.0.1:43285', 'tcp://127.0.0.1:39343'}
2024-09-13 17:01:34,013 - tornado.application - ERROR - Exception in callback <bound method Scheduler.check_worker_ttl of <Scheduler 'tcp://127.0.0.1:40607', workers: 0, cores: 0, tasks: 20>>
Traceback (most recent call last):
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/tornado/ioloop.py", line 939, in _run
    await val
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/scheduler.py", line 8492, in check_worker_ttl
    await self.restart_workers(
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/scheduler.py", line 6454, in restart_workers
    raise TimeoutError(
asyncio.exceptions.TimeoutError: 4/5 nanny worker(s) did not shut down within 30s: {'tcp://127.0.0.1:45409', 'tcp://127.0.0.1:42137', 'tcp://127.0.0.1:43285', 'tcp://127.0.0.1:39343'}
2024-09-13 17:01:34,014 - distributed.nanny - WARNING - Restarting worker
2024-09-13 17:01:34,015 - distributed.nanny - WARNING - Restarting worker
2024-09-13 17:01:34,022 - distributed.nanny - WARNING - Restarting worker
2024-09-13 17:01:34,029 - distributed.nanny - WARNING - Restarting worker
2024-09-13 17:01:47,800 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('run_flexddg-2a0030663990bb64bec0bd855a6d3edf')" coro=<Worker.execute() done, defined at /mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/worker_state_machine.py:3615>> ended with CancelledError
2024-09-13 17:01:51,224 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2024-09-14 00:59:43,679 - distributed.scheduler - WARNING - Worker failed to heartbeat for 566s; attempting restart: <WorkerState 'tcp://127.0.0.1:33699', name: 3, status: running, memory: 0, processing: 2>
2024-09-14 00:59:43,680 - distributed.scheduler - WARNING - Worker failed to heartbeat for 566s; attempting restart: <WorkerState 'tcp://127.0.0.1:40043', name: 0, status: running, memory: 0, processing: 2>
2024-09-14 00:59:43,680 - distributed.scheduler - WARNING - Worker failed to heartbeat for 566s; attempting restart: <WorkerState 'tcp://127.0.0.1:40733', name: 4, status: running, memory: 0, processing: 2>
2024-09-14 00:59:43,680 - distributed.scheduler - WARNING - Worker failed to heartbeat for 566s; attempting restart: <WorkerState 'tcp://127.0.0.1:40905', name: 1, status: running, memory: 0, processing: 2>
2024-09-14 00:59:47,685 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2024-09-14 00:59:47,685 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2024-09-14 00:59:47,686 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2024-09-14 00:59:47,687 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2024-09-14 00:59:47,706 - distributed.nanny - WARNING - Restarting worker
2024-09-14 00:59:47,707 - distributed.nanny - WARNING - Restarting worker
2024-09-14 00:59:47,714 - distributed.nanny - WARNING - Restarting worker
2024-09-14 00:59:47,721 - distributed.nanny - WARNING - Restarting worker
2024-09-14 01:22:31,644 - distributed.scheduler - WARNING - Worker failed to heartbeat for 1211s; attempting restart: <WorkerState 'tcp://127.0.0.1:39095', name: 0, status: running, memory: 0, processing: 2>
2024-09-14 01:22:31,651 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('run_flexddg-83b0c144050cffb0b243b60a367a6a17')" coro=<Worker.execute() done, defined at /mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/worker_state_machine.py:3615>> ended with CancelledError
2024-09-14 01:22:31,655 - distributed.scheduler - WARNING - Removing worker 'tcp://127.0.0.1:39095' caused the cluster to lose already computed task(s), which will be recomputed elsewhere: {'run_flexddg-2a0030663990bb64bec0bd855a6d3edf'} (stimulus_id='handle-worker-cleanup-1726248151.654934')
2024-09-14 01:22:32,053 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('run_flexddg-1de3896ef494a0ca7489264c0356606b')" coro=<Worker.execute() done, defined at /mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/worker_state_machine.py:3615>> ended with CancelledError
2024-09-14 01:22:32,073 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('run_flexddg-0163d913bb0cf6e40a8ffff9d6f62f33')" coro=<Worker.execute() done, defined at /mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/worker_state_machine.py:3615>> ended with CancelledError
2024-09-14 01:22:32,295 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('run_flexddg-4dae7f8281db5da8e77ec6f58dfce255')" coro=<Worker.execute() done, defined at /mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/worker_state_machine.py:3615>> ended with CancelledError
2024-09-14 01:22:35,652 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2024-09-14 01:22:35,661 - distributed.nanny - WARNING - Restarting worker
2024-09-14 01:22:35,689 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2024-09-14 01:22:35,690 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2024-09-14 01:22:35,893 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2024-09-14 05:12:28,906 - distributed.scheduler - WARNING - Worker failed to heartbeat for 674s; attempting restart: <WorkerState 'tcp://127.0.0.1:41607', name: 0, status: running, memory: 0, processing: 2>
2024-09-14 05:12:28,910 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('run_flexddg-7dfc0e2a905d5d4ac789fd4b3d1085a6')" coro=<Worker.execute() done, defined at /mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/worker_state_machine.py:3615>> ended with CancelledError
2024-09-14 05:12:28,913 - distributed.scheduler - ERROR - Task run_flexddg-7dfc0e2a905d5d4ac789fd4b3d1085a6 marked as failed because 4 workers died while trying to run it
Traceback (most recent call last):
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/bin/rosetta_ddg_run", line 33, in <module>
    sys.exit(load_entry_point('RosettaDDGPrediction==0.0.1', 'console_scripts', 'rosetta_ddg_run')())
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/RosettaDDGPrediction-0.0.1-py3.9.egg/RosettaDDGPrediction/rosetta_ddg_run.py", line 523, in main
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/client.py", line 2562, in gather
    return self.sync(
  File "/mnt/rna01/user/others/rosettaDDGPrediction/miniconda3/envs/rosettaDDGPrediction/lib/python3.9/site-packages/distributed/client.py", line 2423, in _gather
    raise exception.with_traceback(traceback)
distributed.scheduler.KilledWorker: Attempted to run task 'run_flexddg-7dfc0e2a905d5d4ac789fd4b3d1085a6' on 4 different workers, but all those workers died while running it. The last worker that attempt to run the task was tcp://127.0.0.1:41607. Inspecting worker logs is often a good next step to diagnose what went wrong. For more information see https://distributed.dask.org/en/stable/killed.html.
2024-09-14 05:12:32,910 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
```

**Comment by elenapapaleo** [comment]
We use slurm too to submit our jobs on different HPC resources but we encountered this problem without being able to solve it yet fully. It might be associated to Dask itself.

**Comment by platanifolia** [comment]
Appreciate your guidance. Thank you very much for your assistance.
