### ISSUE TITLE
Installation issues and ModuleNotFoundFoundError

### ISSUE THREAD

**Issue by jlingford** [ELELAB/RosettaDDGPrediction#74]
Hi,

I believe I'm having issues with installation, which is then causing errors running the modules.

For installation, I've tried using venv, but this has failed for me.
So I've tried conda instead:

```
conda create -n ddg_rosetta python=3.7 rosetta ##install python3.7 and rosetta into virtual env
conda activate ddg_rosetta
python3.7 setup.py install
```
This fails to install and throws numerous errors:

```
File "<fstring>", line 1
    (self.include_dirs=)
                      ^
SyntaxError: invalid syntax
```
The modules are callable, but are missing dependencies:

```
kg_resources/__init__.py", line 870, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyyaml' distribution was not found and is required by RosettaDDGPrediction
```

However, when I repeat the installation with python3.12, the installation works much better, except for an issue with numpy

```
conda create -n ddg_rosetta python=3.12 rosetta ##install python3.12 and rosetta into virtual env
conda activate ddg_rosetta
python3 setup.py install

### error: numpy 2.1.3 is installed but numpy<2.0,>=1.22.3 is required by {'MDAnalysis'} ###
```
After this, the modules are callable, but running them results in an error.

E.g. running `rosetta_ddg_run --help`:

```
Traceback (most recent call last):
  File "/fs04/scratch2/rp24/jamesl2/RosettaDDGPrediction/rp24_scratch2/jamesl2/miniconda/conda/envs/ddg_rosetta/bin/rosetta_ddg_run", line 33, in <module>
    sys.exit(load_entry_point('RosettaDDGPrediction==0.0.1', 'console_scripts', 'rosetta_ddg_run')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fs04/scratch2/rp24/jamesl2/RosettaDDGPrediction/rp24_scratch2/jamesl2/miniconda/conda/envs/ddg_rosetta/bin/rosetta_ddg_run", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/fs04/scratch2/rp24/jamesl2/RosettaDDGPrediction/rp24_scratch2/jamesl2/miniconda/conda/envs/ddg_rosetta/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fs04/scratch2/rp24/jamesl2/RosettaDDGPrediction/rp24_scratch2/jamesl2/miniconda/conda/envs/ddg_rosetta/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/fs04/scratch2/rp24/jamesl2/RosettaDDGPrediction/rp24_scratch2/jamesl2/miniconda/conda/envs/ddg_rosetta/lib/python3.12/site-packages/RosettaDDGPrediction-0.0.1-py3.12.egg/RosettaDDGPrediction/rosetta_ddg_run.py", line 40, in <module>
  File "/fs04/scratch2/rp24/jamesl2/RosettaDDGPrediction/rp24_scratch2/jamesl2/miniconda/conda/envs/ddg_rosetta/lib/python3.12/site-packages/dask-2024.11.2-py3.12.egg/dask/__init__.py", line 3, in <module>
    from dask import config, datasets
  File "/fs04/scratch2/rp24/jamesl2/RosettaDDGPrediction/rp24_scratch2/jamesl2/miniconda/conda/envs/ddg_rosetta/lib/python3.12/site-packages/dask-2024.11.2-py3.12.egg/dask/datasets.py", line 7, in <module>
    from dask.utils import import_required
  File "/fs04/scratch2/rp24/jamesl2/RosettaDDGPrediction/rp24_scratch2/jamesl2/miniconda/conda/envs/ddg_rosetta/lib/python3.12/site-packages/dask-2024.11.2-py3.12.egg/dask/utils.py", line 26, in <module>
    import tlz as toolz
ModuleNotFoundError: No module named 'tlz'
```

Trying to resolve this with `pip install tlz` returns an `ERROR: No matching distribution found for tlz`.
I see there is a pip package called toolz, so I also tried `pip install toolz`, however, this requires even more dependencies which need to be installed first.

I'm not sure how to resolve these issues.
Do you have any insight into why this isn't installing properly?
Do you have a conda requirements file that you can share with specific dependency versions? 

Thanks

**Comment by jlingford** [comment]
Fixed the issues, which were all dependency issues.

```bash
mamba create -n ddg_rosetta
mamba activate ddg_rosetta
mamba install python=3.12
#follow repo's installation instructions (will be incomplete)
python3 setup.py install
# intall rosetta
mamba install -c https://conda.rosettacommons.org rosetta
# install dependencies required by repo
mamba install biopython dask distributed matplotlib MDAnalysis numpy pandas pyyaml seaborn
# one dask dependency is buggy and needs to be updated (discovered this after much pain..)
mamba install -c conda-forge msgpack-python==1.0.5

```

Full list of dependencies:

```yaml
name: ddg_rosetta
channels:
  - conda-forge
  - pkgs/main
  - https://conda.rosettacommons.org
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - arrow-cpp=16.1.0=hc1eb8f0_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.10.55=h721c034_0
  - biopython=1.84=py312h9a8786e_0
  - blas=1.0=openblas
  - bokeh=3.6.0=py312h06a4308_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.4.2=py312ha883a20_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py312h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.9.24=h06a4308_0
  - cftime=1.6.2=py312ha883a20_1
  - click=8.1.7=py312h06a4308_0
  - cloudpickle=3.0.0=py312h06a4308_0
  - contourpy=1.2.0=py312hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - cytoolz=0.12.2=py312h5eee18b_0
  - dask=2024.8.2=py312h06a4308_0
  - dask-core=2024.8.2=py312h06a4308_0
  - dask-expr=1.1.13=py312h06a4308_0
  - dbus=1.13.18=hb2f20db_0
  - distributed=2024.8.2=py312h06a4308_0
  - expat=2.6.3=h6a678d5_0
  - fasteners=0.16.3=pyhd3eb1b0_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonttools=4.51.0=py312h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2024.6.1=py312h06a4308_0
  - gflags=2.2.2=h6a678d5_1
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - glog=0.5.0=h6a678d5_1
  - griddataformats=1.0.2=pyhd8ed1ab_0
  - gsd=3.4.2=py312h66e93f0_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h5py=3.12.1=py312hc0802c4_0
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.12.1=h2b7332f_3
  - heapdict=1.0.1=pyhd3eb1b0_0
  - icu=73.1=h6a678d5_0
  - jinja2=3.1.4=py312h06a4308_1
  - joblib=1.4.2=py312h06a4308_0
  - jpeg=9e=h5eee18b_3
  - kiwisolver=1.4.4=py312h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.9.1=h251f7ec_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.2.0=h77fa898_1
  - libgrpc=1.62.2=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libllvm14=14.0.6=hecde1de_4
  - libnetcdf=4.8.1=h14805e7_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.0=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.1=hfdd30dd_2
  - libzip=1.8.0=h6ac8c49_1
  - libzlib=1.2.13=h4ab18f5_6
  - locket=1.0.0=py312h06a4308_0
  - lz4=4.3.2=py312h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py312h5eee18b_0
  - matplotlib=3.9.2=py312h06a4308_0
  - matplotlib-base=3.9.2=py312h66fe004_0
  - mda-xdrlib=0.2.0=pyhd8ed1ab_0
  - mdanalysis=2.7.0=py312hfb8ada1_1
  - mmtf-python=1.1.3=pyhd8ed1ab_0
  - mrcfile=1.5.3=pyhd8ed1ab_0
  - msgpack-python=1.0.5=py312h8572e83_1
  - mysql=8.4.0=h29a9f33_1
  - ncurses=6.4=h6a678d5_0
  - netcdf4=1.6.2=py312h33ae428_0
  - networkx=3.3=py312h06a4308_0
  - numexpr=2.10.1=py312hd28fd6d_0
  - numpy=1.26.4=py312h2809609_0
  - numpy-base=1.26.4=py312he1a6c75_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.4.0=hb9d3cd8_0
  - orc=2.0.1=h2d29ad5_0
  - packaging=24.1=py312h06a4308_0
  - pandas=2.2.2=py312h526ad5a_0
  - partd=1.4.1=py312h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pillow=11.0.0=py312hfdbf927_0
  - pip=24.2=py312h06a4308_0
  - ply=3.11=py312h06a4308_1
  - psutil=5.9.0=py312h5eee18b_0
  - pyarrow=16.1.0=py312h526ad5a_0
  - pyedr=0.8.0=pyhd8ed1ab_0
  - pyparsing=3.2.0=py312h06a4308_0
  - pyqt=5.15.10=py312h6a678d5_0
  - pyqt5-sip=12.13.0=py312h5eee18b_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.2=hab00c5b_0_cpython
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-lmdb=1.4.1=py312h6a678d5_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.12=5_cp312
  - pytng=0.3.1=py312h40ad5df_2
  - pytz=2024.1=py312h06a4308_0
  - pyyaml=6.0.2=py312h5eee18b_0
  - qt-main=5.15.2=hb6262e9_11
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - rosetta=2024.42+release.3366cf78a3=0
  - s2n=1.3.27=hdbd6064_0
  - scikit-learn=1.5.1=py312h526ad5a_0
  - scipy=1.14.1=py312h2809609_0
  - seaborn=0.13.2=py312h06a4308_0
  - setuptools=75.1.0=py312h06a4308_0
  - sip=6.7.12=py312h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=h6a678d5_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - sqlite=3.45.3=h5eee18b_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - threadpoolctl=3.5.0=py312he106c6f_0
  - tidynamics=1.1.2=pyhd8ed1ab_0
  - tk=8.6.14=h39e8969_0
  - toolz=0.12.0=py312h06a4308_0
  - tornado=6.4.1=py312h5eee18b_0
  - tqdm=4.66.5=py312he106c6f_0
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=15.1.0=py312h5eee18b_0
  - urllib3=2.2.3=py312h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - wheel=0.44.0=py312h06a4308_0
  - xyzservices=2022.9.0=py312h06a4308_1
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zict=3.0.0=py312h06a4308_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=hc292b87_0
```

However, certain files need to be edited because they're out of date.
The three .yaml files in `./RosettaDDGPrediction/config_settings/` need the following Rosetta section to be edited to to reflect the updated rosetta package

```yaml
rosetta:
  # usual Rosetta path for executables (UPDATED)
  execpath: "bin"
  # suffix of the Rosetta executables (UPDATED)
  execsuffix: .cxx11threadserialization.linuxclangrelease

```

Then running the first rosetta_ddg_run step, the -r flag can be set to micromamba env dir:

```bash
rosetta_ddg_run \
    -p pdb_input/wt_monomer.pdb \
    -l muts/muts.txt \
    -cr ./RosettaDDGPrediction/config_run/cartddg2020_ref2015.yaml \
    -cs ./RosettaDDGPrediction/config_settings/rosettampi.yaml \
    -r /home/james/micromamba/envs/ddg_rosetta
```
